# Generated by Django 4.1.3 on 2022-11-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('perfil', models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd')], max_length=20)),
                ('nivel', models.CharField(choices=[('Junior', 'junior'), ('Semisenior', 'semisenior'), ('Senior', 'senior')], max_length=20)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
