# Generated by Django 4.1.3 on 2022-11-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='release_date',
            new_name='pub_date',
        ),
    ]
